apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app
  namespace: default
spec:
  data:
    - remoteRef:
        key: /prod/mongodb-atlas/passwords/root
      secretKey: MONGO_ROOT_PASSWORD
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    immutable: true
