apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notifications
  namespace: flux-system
spec:
  force: true
  interval: 5m
  path: ./notifications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
