configMapGenerator:
  - name: echo-server
    envs:
      - configs.env

images:
  - name: ghcr.io/developer-friendly/echo-server

resources:
  - service.yml
  - deployment.yml

replacements:
  - source:
      kind: ConfigMap
      name: echo-server
      fieldPath: data.PORT
    targets:
      - select:
          name: echo-server
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=echo-server].ports.[name=http].containerPort

commonLabels:
  app.kubernetes.io/name: echo-server
  app.kubernetes.io/instance: echo-server
  app.kubernetes.io/version: 1.0.0
  app.kubernetes.io/component: echo-server
  app.kubernetes.io/part-of: echo-server
  app.kubernetes.io/managed-by: kustomize
