apiVersion: v1
kind: Service
metadata:
  name: ente-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
    - port: 2112
      protocol: TCP
      targetPort: metrics
      name: metrics
