block-list-secret-scan: []
branch: master
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
quiet: true
secrets-scan-file-type: []
skip-check:
  - CKV_TF_1
  - CKV_AWS_273
  - CKV_AZURE_50
  - CKV_AZURE_119
  - CKV2_AZURE_31
  - CKV2_ANSIBLE_3
  - CKV_AWS_108
  - CKV_AWS_356
  - CKV_K8S_21
  - CKV_AWS_337
  - CKV_SECRET_6
  - CKV2_AWS_34
  - CKV2_ANSIBLE_2
  - CKV2_AWS_39
  - CKV2_AWS_38
  - CKV_K8S_12
  - CKV_K8S_43
  - CKV_K8S_25
  - CKV_K8S_40
  - CKV_K8S_10
  - CKV_K8S_14
  - CKV_K8S_11
  - CKV_K8S_8
  - CKV_K8S_20
  - CKV_K8S_38
  - CKV_K8S_13
  - CKV_K8S_9
  - CKV_K8S_22
  - CKV_K8S_37
  - CKV_K8S_29
  - CKV_K8S_30
  - CKV_K8S_31
  - CKV_K8S_28
  - CKV_K8S_23
  - CKV_K8S_35
  - CKV_K8S_22
  - CKV_K8S_37
  - CKV2_K8S_6
  - CKV_K8S_15
  - CKV2_K8S_6
  - CKV2_K8S_6
  - CKV_TF_2
  - CKV_K8S_49
skip-framework: []
skip-path: []
summary-position: top
