repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=600"]
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
        exclude: .*templates/.*j2$
      - id: check-yaml
        args:
          - --allow-multiple-documents
        exclude: mkdocs.yml
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: file-contents-sorter
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
