site_name: Developer Friendly Blog
edit_uri: blob/main/docs/
extra:
  social:
    - icon: octicons/heart-fill-16
      link: https://github.com/sponsors/meysam81/
      name: Sponsor the author!
    - icon: fontawesome/brands/paypal
      link: http://paypal.me/meysamazad
      name: Thank the author!
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/developer-friendly
      name: Follow us on LinkedIn!
    - icon: fontawesome/solid/square-rss
      link: /feed_rss_created.xml
      name: Subscribe to our RSS feed!
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@developer-friendly
      name: Subscribe to our YouTube channel!
    - icon: simple/stackoverflow
      link: https://stackoverflow.com/users/8282345/meysam
      name: Follow us on Stack Overflow!
    - icon: fontawesome/brands/hacker-news
      link: https://news.ycombinator.com/submitted?id=meysamazad
      name: Follow us on Hacker News!
    - icon: fontawesome/solid/envelope
      link: mailto:hi@developer-friendly.blog
      name: Send us an email!
    - icon: fontawesome/brands/slack
      link: https://communityinviter.com/apps/developerfriendly/join-our-slack
      name: Join our Slack community!
  analytics:
    provider: google
    property: !ENV [GA_PROPERTY, ""]
    feedback:
      title: Did you enjoy the content?
      ratings:
        - icon: fontawesome/regular/face-smile-beam
          name: I loved it
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: fontawesome/regular/face-frown
          name: Nope
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/orgs/developer-friendly/discussions/new?category=general&title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
      github: GitHub
      logrocket:
        name: Logrocket
        checked: true
      personalization:
        name: Ads Personalization
        checked: true
  status:
    new: Recently added
extra_javascript:
  - static/js/consent.js
  - static/js/subscribe.js
  - static/js/announce.js
extra_css:
  - static/css/subscribe.css
  - static/css/announce.css
copyright: Copyright &copy; <a href="https://github.com/meysam81">Meysam Azad</a>
plugins:
  - typeset
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - search:
      lang: en
  - tags
  - glightbox
  - offline:
      enabled: !ENV [OFFLINE, false]
  - optimize:
      enabled: !ENV [CI, false]
  - privacy:
      enabled: !ENV [PRIVACY, false]
      assets_exclude:
        - pagead2.googlesyndication.com/*
        - www.googletagmanager.com/*
  - meta:
      enabled: !ENV [CI, false]
  - social:
      enabled: true
      cards: true
      cards_layout: default/variant
      cache: true
      log: !ENV [LOG, false]
      log_level: !ENV [LOG_LEVEL, warn]
      debug: !ENV [DEBUG, false]
      debug_on_build: !ENV [DEBUG_BUILD, false]
  - blog:
      draft: !ENV [DRAFT, false]
      draft_if_future_date: true
      blog_dir: .
      authors_profiles: !ENV [AUTHORS_PROFILE, false]
      post_readtime: true
      blog_toc: true
      post_date_format: long
      archive: true
      archive_pagination: true
      pagination: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
  - rss:
      enabled: true
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      json_feed_enabled: true
      rss_feed_enabled: true
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
      use_git: true
      pretty_print: true
      use_material_social_cards: true
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
      type: date
      fallback_to_build_date: true
  - git-committers:
      repository: developer-friendly/blog
      branch: main
      token: !ENV [GITHUB_TOKEN, ""]
      enabled: !ENV [CI, false]
  - table-reader
  - exclude:
      glob:
        - "**/.terra*"
remote_branch: gh-pages
remote_name: origin
repo_name: GitHub
repo_url: https://github.com/developer-friendly/blog
site_url: !ENV [URL, https://developer-friendly.blog]
site_author: meysam@developer-friendly.blog (Meysam Azad)
site_description: >-
  Kubernetes, GitOps, CI/CD, Infrastructure as Code (IaC), and Site Reliability
  Engineering topics from seven years of production deployments.
strict: true
theme:
  language: en
  name: material
  custom_dir: overrides
  logo: assets/logo.webp
  favicon: assets/favicon.ico
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.instant.preview
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  # - material.extensions.preview
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.progressbar
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.snippets:
      url_download: !ENV [URL_DOWNLOAD, false]
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - index.md
  - terms.md
  - privacy.md
watch:
  - overrides
  - includes
