site_name: Developer Friendly Blog
edit_uri: blob/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/developer-friendly
      name: Check out our GitHub!
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/developerfriendly/
      name: Check out our Docker images!
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/developer-friendly
      name: Follow us on LinkedIn!
    - icon: fontawesome/brands/slack
      link: https://communityinviter.com/apps/developerfriendly/join-our-slack
      name: Join our Slack!
    - icon: fontawesome/solid/square-rss
      link: /feed_rss_created.xml
      name: Subscribe to our RSS feed!
  analytics:
    provider: google
    property: !ENV [GA_PROPERTY, ""]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/developer-friendly/blog/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Analytics
      github: GitHub
      logrocket:
        name: Logrocket
        checked: true
      # TODO: Until Google Adsense team considers my content "valuable", I get
      # no revenue, nor any ads will be placed on my site. So, I'm turning it
      # off to avoid harrassing my readers.
      # adstorage:
      #   name: Google AdSense - Storage
      #   checked: true
      # aduserdata:
      #   name: Google AdSense - User Data
      #   checked: true
      # adpersonalization:
      #   name: Google AdSense - Personalization
      #   checked: true
      # analyticsstorage:
      #   name: Google Analytics - Storage
      #   checked: true
extra_javascript:
  - static/js/consent.js
copyright: Copyright &copy; <a href="https://github.com/meysam81">Meysam Azad</a>
plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - search:
      lang: en
  - tags
  - glightbox
  - offline:
      enabled: !ENV [OFFLINE, false]
  - privacy:
      enabled: !ENV [OFFLINE, false]
  - social:
      enabled: !ENV [CI, false]
      cards: true
  - blog:
      blog_dir: .
      # authors_profiles: true
      post_readtime: true
      blog_toc: true
      post_date_format: long
      post_readtime_words_per_minute: 238
      archive: true
      # archive_pagination: true
      pagination: true
  - rss:
      enabled: true
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
      type: date
      fallback_to_build_date: true
  - git-committers:
      repository: developer-friendly/blog
      branch: main
      token: !ENV [GITHUB_TOKEN, ""]
      enabled: !ENV [CI, false]
  - table-reader
remote_branch: gh-pages
remote_name: origin
repo_name: GitHub
repo_url: https://github.com/developer-friendly/blog
site_url: https://developer-friendly.blog
site_author: meysam@developer-friendly.blog (Meysam Azad)
site_description: >-
  A blog about SRE, Kubernetes, CI/CD, GitOps, Cloud Native, and more!
# site_dir: mkdocs
strict: true
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.progressbar
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.snippets:
      url_download: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
