configMapGenerator:
  - name: kratos-config
    files:
      - config.yml=kratos-server-config.yml
    behavior: replace

resources:
  - https://github.com/meysam81/kustomizations//kratos/overlays/default/?ref=v1.7.2
  - ingress.yml

patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dev
    target:
      kind: Deployment

namespace: default
