apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keto-secrets
spec:
  data:
    - remoteRef:
        key: /keto/dsn
      secretKey: DSN
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
