apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  name: rules.oathkeeper.ory.sh
spec:
  group: oathkeeper.ory.sh
  names:
    kind: Rule
    listKind: RuleList
    plural: rules
    singular: rule
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Rule is the Schema for the rules API
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: RuleSpec defines the desired state of Rule
              properties:
                authenticators:
                  items:
                    description:
                      Authenticator represents a handler that authenticates
                      provided credentials.
                    properties:
                      config:
                        description:
                          Config configures the handler. Configuration keys
                          vary per handler.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      handler:
                        description: Name is the name of a handler
                        type: string
                    required:
                      - handler
                    type: object
                  type: array
                authorizer:
                  description:
                    Authorizer represents a handler that authorizes the subject
                    ("user") from the previously validated credentials making the request.
                  properties:
                    config:
                      description:
                        Config configures the handler. Configuration keys
                        vary per handler.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    handler:
                      description: Name is the name of a handler
                      type: string
                  required:
                    - handler
                  type: object
                configMapName:
                  description:
                    ConfigMapName points to the K8s ConfigMap that contains
                    these rules
                  maxLength: 253
                  minLength: 1
                  pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                  type: string
                errors:
                  items:
                    description:
                      Error represents a handler that is responsible for
                      executing logic when an error happens.
                    properties:
                      config:
                        description:
                          Config configures the handler. Configuration keys
                          vary per handler.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      handler:
                        description: Name is the name of a handler
                        type: string
                    required:
                      - handler
                    type: object
                  type: array
                match:
                  description: Match defines the URL(s) that an access rule should match.
                  properties:
                    methods:
                      description:
                        Methods represent an array of HTTP methods (e.g.
                        GET, POST, PUT, DELETE, ...)
                      items:
                        type: string
                      type: array
                    url:
                      description:
                        URL is the URL that should be matched. It supports
                        regex templates.
                      type: string
                  required:
                    - methods
                    - url
                  type: object
                mutators:
                  items:
                    description:
                      Mutator represents a handler that transforms the HTTP
                      request before forwarding it.
                    properties:
                      config:
                        description:
                          Config configures the handler. Configuration keys
                          vary per handler.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      handler:
                        description: Name is the name of a handler
                        type: string
                    required:
                      - handler
                    type: object
                  type: array
                upstream:
                  description:
                    Upstream represents the location of a server where requests
                    matching a rule should be forwarded to.
                  properties:
                    preserveHost:
                      description:
                        PreserveHost includes the host and port of the url
                        value if set to false. If true, the host and port of the ORY
                        Oathkeeper Proxy will be used instead.
                      type: boolean
                    stripPath:
                      description:
                        StripPath replaces the provided path prefix when
                        forwarding the requested URL to the upstream URL.
                      type: string
                    url:
                      description: URL defines the target URL for incoming requests
                      maxLength: 256
                      minLength: 3
                      pattern: ^(?:https?:\/\/)?(?:[^@\/\n]+@)?(?:www\.)?([^:\/\n]+)
                      type: string
                  required:
                    - url
                  type: object
              required:
                - match
              type: object
            status:
              description: RuleStatus defines the observed state of Rule
              properties:
                validation:
                  description: Validation defines the validation state of Rule
                  properties:
                    valid:
                      type: boolean
                    validationError:
                      type: string
                  type: object
              type: object
          type: object
      served: true
      storage: true
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  name: oathkeeper-maester
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  name: oathkeeper-maester-role
rules:
  - apiGroups:
      - oathkeeper.ory.sh
    resources:
      - rules
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  name: oathkeeper-maester-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oathkeeper-maester-role
subjects:
  - kind: ServiceAccount
    name: oathkeeper-maester
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  name: oathkeeper-maester-metrics
  namespace: default
spec:
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: oathkeeper-maester
    app.kubernetes.io/instance: oathkeeper-maester
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: oathkeeper-maester
    app.kubernetes.io/part-of: oathkeeper-maester
    app.kubernetes.io/version: v1.0.0
  name: oathkeeper-maester
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: oathkeeper-maester
      app.kubernetes.io/instance: oathkeeper-maester
      app.kubernetes.io/managed-by: Kustomize
      app.kubernetes.io/name: oathkeeper-maester
      app.kubernetes.io/part-of: oathkeeper-maester
      app.kubernetes.io/version: v1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: oathkeeper-maester
        app.kubernetes.io/instance: oathkeeper-maester
        app.kubernetes.io/managed-by: Kustomize
        app.kubernetes.io/name: oathkeeper-maester
        app.kubernetes.io/part-of: oathkeeper-maester
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
        - args:
            - --metrics-addr=0.0.0.0:8080
            - controller
            - --rulesConfigmapName=oathkeeper-rules
            - --rulesConfigmapNamespace=$(POD_NAMESPACE)
          command:
            - /manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: oryd/oathkeeper-maester:v0.1.11
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: metrics
            timeoutSeconds: 1
          name: oathkeeper-maester
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: metrics
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              set -eux

              cm=$(kubectl get configmap oathkeeper-rules -n $POD_NAMESPACE -o jsonpath='{.metadata.name}' 2>/dev/null || true)

              cat <<'EOF' > access-rules.json
              []
              EOF

              if [ -z "$cm" ]; then
                kubectl create configmap oathkeeper-rules --from-file=access-rules.json -n $POD_NAMESPACE
              else
                echo "ConfigMap/oathkeeper-rules already present"
              fi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: bitnami/kubectl:1.32.0
          name: initial-rules
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          workingDir: /tmp
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: oathkeeper-maester
      terminationGracePeriodSeconds: 120
      volumes:
        - emptyDir: {}
          name: tmp
