---
- name: Create acme group
  group:
    name: acme
    state: present
    system: true
- name: Create acme user
  user:
    name: acme
    state: present
    group: acme
    shell: /bin/false
    home: "{{ acme_home }}"
    system: true
    create_home: true
- name: Create an standalone server to respond to challenges
  ansible.builtin.template:
    src: wellknown-server.service.j2
    dest: /etc/systemd/system/wellknown-server.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart wellknown-server
- name: Start the wellknown-server
  ansible.builtin.systemd:
    name: wellknown-server
    state: started
    enabled: true
    daemon_reload: true
# - name: Fetch TLS Certificate for {{ domain_name }}
#   community.crypto.acme_certificate:
