apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
spec:
  data:
    - remoteRef:
        key: /postgres/ente/superuser/username
      secretKey: username
    - remoteRef:
        key: /postgres/ente/superuser/password
      secretKey: password
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    template:
      type: kubernetes.io/basic-auth
