apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-webhooks
spec:
  data:
    - remoteRef:
        key: /slack/developer-friendly/webhooks/alerts
      secretKey: slackWebhook
    - remoteRef:
        key: /discord/developer-friendly/webhooks/info
      secretKey: discordWebhook
  refreshInterval: 6m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
