apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
      version: 58.x
  install:
    crds: Create
    createNamespace: true
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 10
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  test:
    enable: true
    ignoreFailures: true
    timeout: 1m
  timeout: 5m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfigMatcherStrategy:
          type: None
