apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmscrape
spec:
  extraArgs:
    promscrape.maxScrapeSize: 32MiB
  selectAllByDefault: true
  remoteWrite:
    - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
      basicAuth:
        password:
          key: password
          name: grafana-cloud-secret
          optional: false
        username:
          key: username
          name: grafana-cloud-secret
          optional: false
