access_rules:
  matching_strategy: regexp
  repositories:
    - file:///etc/rules/access-rules.json
authenticators:
  cookie_session:
    config:
      check_session_url: http://kratos-public/sessions/whoami
      extra_from: "@this"
      force_method: GET
      only:
        - ory_kratos_session
      preserve_path: true
      preserve_query: true
      subject_from: identity.id
    enabled: true
authorizers:
  allow:
    enabled: true
errors:
  fallback:
    - redirect
  handlers:
    redirect:
      config:
        return_to_query_param: return_to
        to: http://auth.localhost.com:8080/login
      enabled: true
mutators:
  header:
    config:
      headers:
        x-user-id: "{{ print .Subject }}"
    enabled: true
serve:
  api:
    port: 4456
  prometheus:
    port: 9000
  proxy:
    port: 4455
    timeout:
      read: 60m
      idle: 60m
      write: 60m
    cors:
      enabled: true
      allowed_headers:
        - accept
        - content-type
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowed_origins:
        - http://*.localhost.com
      allow_credentials: true
      debug: false
