authors:
  meysam@developer-friendly.blog (Meysam Azad):
    name: Meysam Azad
    description: Writer
    avatar: https://avatars.githubusercontent.com/u/30233243
    url: https://github.com/meysam81
