configMapGenerator:
  - files:
      - ./keto-server-config.yml
    name: keto-config

images:
  - name: oryd/keto
    newTag: v0.12.0

resources:
  - externalsecret.yml
  - service-read.yml
  - service-write.yml
  - deployment.yml
  - httproute-read.yml
  - httproute-write.yml

commonLabels:
  app.kubernetes.io/component: keto
  app.kubernetes.io/instance: keto
  app.kubernetes.io/managed-by: Kustomize
  app.kubernetes.io/name: keto
  app.kubernetes.io/version: v0.12.0
