name: Selective Builds
description: Calculate the changed services comparing the contents of files to the previous run.
author: Meysam Azad
branding:
  icon: sliders
  color: orange
inputs:
  path:
    description: The directory to look for applications
    required: true
    default: "."
  redis-host:
    description: The host of the redis server
    required: true
  redis-port:
    description: The port of the redis server
    required: false
    default: "6379"
  redis-password:
    description: The password of the redis server
    required: true
  redis-ssl:
    description: Whether to use SSL for the redis connection
    required: false
    default: "false"
  mode:
    description: Whether to capture the changes or to submit them to datastore (mark|submit)
    required: false
    default: "mark"
  exclusions:
    description: A line separated list of patterns to exclude when finding apps
    required: false
    default: ""
  store-key:
    description: The key to store the changes in the redis server
    required: false
    default: app-caches
outputs:
  apps:
    description: A comma list of applications that need rebuild.
runs:
  using: node20
  main: dist/index.js
