resources:
  - https://github.com/meysam81/kustomizations//oathkeeper-maester/overlays/default/?ref=v1.8.0

replacements:
  - source:
      kind: ServiceAccount
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterRoleBinding
        fieldPaths:
          - subjects.[name=oathkeeper-maester].namespace

namespace: default
