- name: Include host specific variables
  ansible.builtin.include_vars:
    file: vars-{{ ansible_architecture }}.yml
- name: Download vmutils
  ansible.builtin.get_url:
    url: "{{ vmutils_url }}"
    dest: "/tmp/{{ vmutils_url | basename }}"
    mode: "0444"
    owner: root
    group: root
  register: vmutils_download
- name: Extract binaries
  ansible.builtin.unarchive:
    src: "{{ vmutils_download.dest }}"
    dest: /usr/local/bin/
    remote_src: true
    mode: "0755"
    owner: root
    group: root
    extra_opts:
      - vmagent-prod
      - vmalert-prod
      - vmalert-tool-prod
      - vmauth-prod
      - vmbackup-prod
      - vmrestore-prod
      - vmctl-prod
- name: Ensure victoria-metrics relevant dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /var/lib/victoria-metrics
    - /etc/victoria-metrics
- name: Copy service file
  ansible.builtin.template:
    src: vmagent.service.j2
    dest: /etc/systemd/system/vmagent.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart vmagent service
- name: Copy config file
  ansible.builtin.template:
    src: vmagent.yml.j2
    dest: /etc/victoria-metrics/vmagent.yml
    owner: root
    group: root
    mode: "0444"
  notify: Restart vmagent service
- name: Start vmagent service
  ansible.builtin.systemd:
    name: vmagent
    state: started
    enabled: true
    daemon_reload: true
