apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: standalone
spec:
  retentionPeriod: "1"
  removePvcAfterDelete: true
  extraArgs:
    dedup.minScrapeInterval: 10s
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
