route:
  receiver: "null"
  group_by:
    - namespace
  continue: false
  routes:
    - receiver: monitoring/alertmanager/slack-error
      group_by:
        - alertname
        - app
        - env
        - severity
      matchers:
        - severity=~"critical|warning|error|info"
      continue: false
      routes:
        - receiver: monitoring/alertmanager/slack-info
          match:
            severity: info
          continue: false
        - receiver: monitoring/alertmanager/slack-error
          match:
            severity: error
          continue: false
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    - receiver: "null"
      matchers:
        - alertname="Watchdog"
      continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
  - name: "null"
  - name: monitoring/alertmanager/slack-error
    slack_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
          enable_http2: true
        api_url: <secret>
        channel: "#alerts"
        username: '{{ template "slack.default.username" . }}'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: "{{ .CommonAnnotations.summary }}"
        title_link: "{{ .CommonAnnotations.runbook_url }}"
        pretext: '{{ template "slack.default.pretext" . }}'
        text: |-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
          {{ end }}
        short_fields: false
        footer: '{{ template "slack.default.footer" . }}'
        fallback: '{{ template "slack.default.fallback" . }}'
        callback_id: '{{ template "slack.default.callbackid" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
        link_names: false
  - name: monitoring/alertmanager/slack-info
    slack_configs:
      - send_resolved: false
        http_config:
          follow_redirects: true
          enable_http2: true
        api_url: <secret>
        channel: "#notifications"
        username: '{{ template "slack.default.username" . }}'
        color: good
        title: "{{ .CommonAnnotations.summary }}"
        title_link: "{{ .CommonAnnotations.runbook_url }}"
        pretext: '{{ template "slack.default.pretext" . }}'
        text: |-
          {{ range .Alerts }}
          *Info:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
          {{ end }}
        short_fields: false
        footer: '{{ template "slack.default.footer" . }}'
        fallback: '{{ template "slack.default.fallback" . }}'
        callback_id: '{{ template "slack.default.callbackid" . }}'
        icon_emoji: '{{ template "slack.default.iconemoji" . }}'
        icon_url: '{{ template "slack.default.iconurl" . }}'
        link_names: false
