apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: vmagent
      namespace: default
    spec:
      rules:
        - host: vmagent.localhost.com
          http:
            paths:
              - backend:
                  service:
                    name: oathkeeper-proxy
                    port:
                      name: http
                path: /
                pathType: Prefix
  - apiVersion: oathkeeper.ory.sh/v1alpha1
    kind: Rule
    metadata:
      name: vmagent
      namespace: default
    spec:
      authenticators:
        - handler: cookie_session
      authorizer:
        handler: allow
      errors:
        - handler: redirect
      match:
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        url: http://vmagent.localhost</?.*>
      mutators:
        - handler: header
      upstream:
        preserveHost: true
        url: http://vmagent-victoria-metrics-k8s-stack:8429
