---
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/valuesFrom/name
        kind: HelmRelease
      - path: /spec/values/deployment/extraVolumes/configMap/name
        kind: HelmRelease
      - path: /spec/values/statefulSet/extraVolumes/configMap/name
        kind: HelmRelease
