apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-standalone
  namespace: flux-system
spec:
  force: false
  interval: 5m
  path: ./victoria-metrics-standalone
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
  wait: true
