ansible_host: "{{ private_ip_address }}"

ansible_ssh_common_args: >-
  -o ProxyCommand="ssh
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o LogLevel=ERROR
  -i {{ bastion_host.ansible_ssh_private_key_file }}
  -W %h:%p
  -q {{ bastion_host.ansible_user }}@{{ bastion_host.ansible_host }}"
