apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: error
spec:
  eventMetadata:
    severity: error
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
      namespace: flux-system
    - kind: Kustomization
      name: "*"
      namespace: flux-system
    - kind: HelmRelease
      name: "*"
      namespace: flux-system
  providerRef:
    name: alertmanager
