name: cronitor

concurrency:
  cancel-in-progress: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
  group: cronitor-${{ github.ref_name }}-${{ github.event_name }}

on:
  workflow_run:
    workflows: ["ci"]
    types: [requested, completed]
permissions:
  contents: write

jobs:
  cronitor:
    if: |
      github.repository == 'developer-friendly/blog' &&
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - name: Send execution details to the Cronitor for Github Actions agent
        uses: cronitorio/monitor-github-actions@v7
        with:
          event: ${{ toJSON(github.event) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cronitor_key: ${{ secrets.CRONITOR_API_KEY }}
          cronitor_group: actions
          cronitor_notify: slack
